#!/bin/bash
#PBS -P c07
#PBS -q normal
#PBS -l walltime=00:04:00
#PBS -l mem=10GB
#PBS -l wd
#PBS -l ncpus=16

source ~/prof/x1016final_ulfm1.1.profile


APP=conflict
places_per_socket=8

pl=16
app_iter=32
repeat_test_runs=10
victim_places=15,7,5,8
victim_iters=5,10,15,20

#########output folder#######
DIR=~/data_store/output
export OUTPUT_DIR=${DIR}
mkdir $OUTPUT_DIR

export X10_EXIT_BY_SIGKILL=1

cd ~/data_store/x10-resilient-store/test
args="-m $app_iter -c 0 -vp $victim_places -vi $victim_iters"
output_file_name=$OUTPUT_DIR/warmNoConflict_${APP}_p${pl}_Resilient.out

for repeat_count in $(seq "$repeat_test_runs");
do
    X10_RESILIENT_MODE=1 \
    X10_NUM_IMMEDIATE_THREADS=1 \
    DS_ALL_VERBOSE=0 \
    FORCE_ONE_PLACE_PER_NODE=1 \
    mpirun -np $((pl)) -am ft-enable-mpi --mca errmgr_rts_hnp_proc_fail_xcast_delay 0 --bind-to-core -npersocket $places_per_socket \
    --mca btl openib,sm,self ./TestKillMultiplePlaces.o $args >> "$output_file_name"
done


